export const START_LOAD_DICTIONARY = 'START_LOAD_DICTIONARY';
export const LOAD_DICTIONARY_SUCCESS= 'LOAD_DICTIONARY_SUCCESS=';
export const LOAD_DICTIONARY_FAIL = 'LOAD_DICTIONARY_FAIL';
export const GET_DICTIONARY_FROM_LOCALSTORE = 'GET_DICTIONARY_FROM_LOCALSTORE';